# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np
print(np.version)
print(np.show_config)

<module 'numpy.version' from '/usr/local/lib/python3.11/dist-packages/numpy/version.py'>
<function show at 0x7966523b56c0>


#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
arr3 = np.zeros(9)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr4 = np.random.rand(2, 4)
print(arr4.size)
print(arr4.itemsize)

8
8


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
arr6 = np.zeros(12)
arr6[6] = 1
arr6

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr7 = np.arange(20, 59)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



In [ ]:
arr8 = np.arange(20, 31)
arr8[::-1]

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

`💡Ishora` array[::-1]

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr9 = np.arange(12, 21)
re_arr = arr9.reshape(3,3)
re_arr

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
arr10 = [3, 7, 0, 0, 9, 0]
np.nonzero(arr10)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
arr11 = np.random.randn(2,2,2)
arr11

array([[[-0.69684834, -0.03063214],
        [-0.17852814, -2.03031636]],

       [[ 0.9779834 , -0.00267733],
        [ 0.42516311,  0.96670965]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr12 = np.random.randn(9,9)
print("Katta qiymat:", arr12.min())
print("Kichik qiymat:", arr12.max())

Katta qiymat: -3.0138889507571007
Kichik qiymat: 2.3767822025345375


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
0 * np.nan   # nan qiymat qaytaradi
np.nan == np.nan  # false  qiymat qaytaradi
np.inf > np.nan # false qiymat qaytaradi
np.nan - np.nan # nan qiymat qaytaradi
np.nan in set([np.nan]) # True qiymat qaytaradi
0.7 == 7 * 0.1  # false qiymat qaytaradi

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr14_1 = np.random.randint(1, 100, (6, 3))
print("a= ", arr14_1.reshape(6, 3), end='')
arr14_2 = np.random.randint(1, 100, (3, 4))
print("b= ", arr14_2.reshape(3, 4), end='')
c = arr14_1.dot(arr14_2)
print("a x b =", c)

a=  [[42 70 47]
 [12 28 89]
 [19 56 38]
 [46 75 64]
 [32 17 69]
 [36 24 65]]b=  [[75 98 53 54]
 [54 10 33 69]
 [32 38 42  9]]a x b = [[8434 6602 6510 7521]
 [5260 4838 5298 3381]
 [5665 3866 4451 5232]
 [9548 7690 7601 8235]
 [5526 5928 5155 3522]
 [6076 6238 5430 4185]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) # Bu misol natijasi yani sum(iterable, start )
from numpy import *
print(sum(range(5), -1)) # bu yerda axis =-1 qilib hisoblaydi range(5) funksiyasini to'liq hisoblaydi

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a_arr = np.arange(2)
b_arr = np.arange(2, 4)
result = np.where(a_arr > b_arr, "True", "False")
print(result)
result_a = np.where(a_arr >= b_arr, "True", "False")
print(result_a)
result_b = np.where(a_arr < b_arr, "True", "False")
print(result_b)
result_c = np.where(a_arr <= b_arr, "True", "False")
print(result_c)


['False' 'False']
['False' 'False']
['True' 'True']
['True' 'True']


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0) # 0/0 bo'lib bo'lmaydi shuning uchun nan qiymat qaytaradi
np.array(0) // np.array(0)


<ipython-input-65-0c51f2b6c625>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0) # 0/0 bo'lib bo'lmaydi shuning uchun nan qiymat qaytaradi
<ipython-input-65-0c51f2b6c625>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [ ]:
np.array([np.nan]).astype(int).astype(float) # bu yerda nan qiymatni integerga uzgartirdi va yana floatga o'zgartirdi shuning uchun tasodifiy qiymat qaytardi

<ipython-input-67-d6c12c5a6b81>:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float) # bu yerda nan qiymatni integerga uzgartirdi va yana floatga o'zgartirdi shuning uchun tasodifiy qiymat qaytardi


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
arr18_1 = np.arange(1, 5)
arr18_2 = np.arange(3, 6)
np.intersect1d(arr18_1, arr18_2)

array([3, 4])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
arr19 = np.random.rand(4)
print(np.floor(arr19))
print(arr19.astype(int))
print(np.trunc(arr19))

[0. 0. 0. 0.]
[0 0 0 0]
[0. 0. 0. 0.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
arr20 = np.arange(0, 2, 2/9).reshape(3,3)
arr20

array([[0.        , 0.22222222, 0.44444444],
       [0.66666667, 0.88888889, 1.11111111],
       [1.33333333, 1.55555556, 1.77777778]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
arr21 = np.array([21, 32, 34, 12, 56, 45, 98, 67, 75, 43, 2])
arr21.sort()
arr21

array([ 2, 12, 21, 32, 34, 43, 45, 56, 67, 75, 98])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
A = np.array([2,1,3,5,6,74,3])
B = np.array([2,3,4,5,1,3,9])
np.allclose(A, B)
np.array_equal(A, B)

False

In [ ]:
A_1 = np.random.rand(4)
B_1 = np.random.rand(4)
np.allclose(A_1, B_1)
np.array_equal(A_1, B_1)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
arr23_1 = np.random.randint(1, 100, (6, 3))
arr23_2 = np.random.randint(1, 100, (3, 4))
results = np.dot(arr23_1, arr23_2)
results

array([[13996,  7406, 11186,  7448],
       [13653,  8092, 14353, 10315],
       [ 6224,  2695,  5944,  2341],
       [11929,  5950,  9769,  5641],
       [ 7516,  6055, 12286, 10639],
       [10840,  6083, 11645,  7532]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
arr24 = np.random.randint(1, 100, size=5)

max_arr =np.argmax(arr24)
print("Eng katta qiymat", arr24[max_arr])
arr24[max_arr] = 0
arr24


Eng katta qiymat 81


array([12, 22,  0, 30, 18])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
data = np.datetime64('today')
yesterday = data - np.timedelta64(1, "D")
tmorrow = data + np.timedelta64(1, 'D')
print('bugungi sana: ', data)
print('kechagi sana: ', yesterday)
print('ertangi sana: ', tmorrow)

bugungi sana:  2025-02-17
kechagi sana:  2025-02-16
ertangi sana:  2025-02-18


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
data26 = np.arange('2016-01-01', '2016-02-01', dtype='datetime64[D]')
data26

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
arr27 = np.random.randn(5)
print(np.floor(arr27))
print(arr27.astype(int))
print(np.trunc(arr27))

[ 0.  1.  0. -1. -1.]
[0 1 0 0 0]
[ 0.  1.  0. -0. -0.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
 %time np.sum(np.arange(5))
 %time np.add.reduce(np.arange(5))

CPU times: user 970 µs, sys: 0 ns, total: 970 µs
Wall time: 906 µs
CPU times: user 39 µs, sys: 3 µs, total: 42 µs
Wall time: 58.2 µs


10

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
arr29 = np.array([1,2,3,4,5])
new_arra =np.array([])
for x in arr29:
  new_arra = np.append(new_arra, [x, 0, 0, 0])
print(new_arra)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
strided_arr = np.lib.stride_tricks.as_strided(a, shape=(11, 4), strides=(8,8))
strided_arr

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

`💡Ishora` stride_tricks.as_strided

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
arr_data = np.array([1,1,1,2,2,2,4,4,4,5,5,5,5,7,7,7,7,9,9,9,9])
arr_data1 =np.bincount(arr_data)
print(arr_data1)
np.argmax(arr_data1)

[0 3 3 0 3 4 0 4 0 4]


5

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`